import 'package:flutter/material.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget2.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedLOADMOREWidget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedOrciVariusNatoqePenatibusWidget2.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedSedutperspiciatisundeomnisistenatuserrorsitvoluptatemac.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedOrciVariusNatoqePenatibusWidget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedLoremIpsumDolorSitAmetWidget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedLATESTNEWSWidget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget1.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedOrciVariusNatoqePenatibusWidget3.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedOrciVariusNatoqePenatibusWidget4.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget3.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget4.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedPOPULARWidget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedOrciVariusNatoqePenatibusWidget1.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/figma2flutlabapp/generatedandroid1widget/generated/Generated9Maret2021Widget5.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1788.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1788.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 80.0,
                                    right: null,
                                    bottom: null,
                                    width: 320.0,
                                    height: 320.0,
                                    child: GeneratedRectangle5Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 420.0,
                                    right: null,
                                    bottom: null,
                                    width: 322.0,
                                    height: 23.0,
                                    child:
                                        GeneratedLoremIpsumDolorSitAmetWidget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 707.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 461.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget1(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 837.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget2(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 967.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget3(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 1097.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget4(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 1227.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 18.0,
                                    child: Generated9Maret2021Widget5(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 495.0,
                                    right: null,
                                    bottom: null,
                                    width: 322.0,
                                    height: 72.0,
                                    child:
                                        GeneratedSedutperspiciatisundeomnisistenatuserrorsitvoluptatemac(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 605.0,
                                    right: null,
                                    bottom: null,
                                    width: 180.0,
                                    height: 50.0,
                                    child: GeneratedLATESTNEWSWidget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 1416.0,
                                    right: null,
                                    bottom: null,
                                    width: 130.0,
                                    height: 53.0,
                                    child: GeneratedPOPULARWidget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 656.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 110.0,
                                    child: GeneratedRectangle6Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 786.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 110.0,
                                    child: GeneratedRectangle7Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 916.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 110.0,
                                    child: GeneratedRectangle8Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 1046.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 110.0,
                                    child: GeneratedRectangle9Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 1176.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 110.0,
                                    child: GeneratedRectangle10Widget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 657.0,
                                    right: null,
                                    bottom: null,
                                    width: 192.0,
                                    height: 68.0,
                                    child:
                                        GeneratedOrciVariusNatoqePenatibusWidget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 787.0,
                                    right: null,
                                    bottom: null,
                                    width: 192.0,
                                    height: 68.0,
                                    child:
                                        GeneratedOrciVariusNatoqePenatibusWidget1(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 917.0,
                                    right: null,
                                    bottom: null,
                                    width: 192.0,
                                    height: 68.0,
                                    child:
                                        GeneratedOrciVariusNatoqePenatibusWidget2(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 1047.0,
                                    right: null,
                                    bottom: null,
                                    width: 192.0,
                                    height: 68.0,
                                    child:
                                        GeneratedOrciVariusNatoqePenatibusWidget3(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 1177.0,
                                    right: null,
                                    bottom: null,
                                    width: 192.0,
                                    height: 68.0,
                                    child:
                                        GeneratedOrciVariusNatoqePenatibusWidget4(),
                                  ),
                                  Positioned(
                                    left: 105.0,
                                    top: 1326.0,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 50.0,
                                    child: GeneratedRectangle11Widget(),
                                  ),
                                  Positioned(
                                    left: 140.0,
                                    top: 1344.0,
                                    right: null,
                                    bottom: null,
                                    width: 81.0,
                                    height: 17.0,
                                    child: GeneratedLOADMOREWidget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 1484.0,
                                    right: null,
                                    bottom: null,
                                    width: 320.0,
                                    height: 224.0,
                                    child: GeneratedFrame1Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 360.0,
              height: 60.0,
              child: GeneratedGroup7Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 60.0,
              child: GeneratedGroup6Widget(),
            )
          ]),
    ));
  }
}
